### ISSUE TITLE
Getting ERROR    GStreamer error: gst-resource-error-quark: Could not open resource for reading. (5)

### ISSUE THREAD

**Issue by GijsTimmers** [unusualcomputers/unusualcomputers#3]
Using the latest git version of mopidymixcloud.

Getting this error.

Log:

```
  Got ERROR bus message: error=u'gst-resource-error-quark: Could not open resource for reading. (5)' debug=u'gstsouphttpsrc.c(1333): gst_soup_http_src_parse_status (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin3/GstSoupHTTPSrc:source:\n (429), URL: http://download.mixcloud-downloader.com/d/mixcloud/Mind_Warp/mind-warp-336-the-best-of-2017-new/, Redirect to: (NULL)'
ERROR    2018-03-18 14:27:03,486 [7594:MainThread] mopidy.audio.gst
  GStreamer error: gst-resource-error-quark: Could not open resource for reading. (5)
```

It still worked fine this morning, no clue what went wrong.

**Comment by unusualcomputers** [comment]
thanks for reporting and apologies for the delay.

this does look odd, possibly something wrong with mixcloud downloader, will check and report back soon.

**Comment by unusualcomputers** [comment]
tested it in several ways and this works fine for me. right now it looks like there is a problem on your side to do with the internet connection or possibly mixcloud-downloader was down.
can you try pasting the link  http://download.mixcloud-downloader.com/d/mixcloud/Mind_Warp/mind-warp-336-the-best-of-2017-new/ in your browser please? It should offer to either play or download the file if it doesn't the problem is your internet access. we can take it from there.
